function giftExchange(list, mail, password)
% Randomize list and send emails to all secret santas!
% SYNTAX
% giftexchange(list, mail, password)
% INPUTS
% list      Cell with names and e-mail adresses organized as follows:
%           {
%           'Name1' 'email1';
%           'Name2' 'email2';
%           ...
%           'NameN' 'emailN'
%           };
% mail      Your GMail email address
% password  Your GMail password
% OUTPUTS
% none

pos = (1:length(list))';
pos2 = (randperm(length(list)))';
while any(pos == pos2)
    disp('Try and error!!!')
    disp([pos pos2])
    pos2 = (randperm(length(list)))';
end
for iContacts=1:length(list),
    list2{iContacts,1} = list{pos2(iContacts),1};
    list2{iContacts,2} = list{pos2(iContacts),2};
    list3{iContacts+1,1} = list{iContacts,1};
    list3{iContacts+1,2} = list2{iContacts,1};
end
list3{1,1} = 'Donors';
list3{1,2} = 'Acceptors';
disp(list3)

% Then this code will set up the preferences properly:
setpref('Internet','E_mail',mail);
setpref('Internet','SMTP_Server','smtp.gmail.com');
setpref('Internet','SMTP_Username',mail);
setpref('Internet','SMTP_Password',password);
props = java.lang.System.getProperties;
props.setProperty('mail.smtp.auth','true');
props.setProperty('mail.smtp.socketFactory.class', 'javax.net.ssl.SSLSocketFactory');
props.setProperty('mail.smtp.socketFactory.port','465');

fprintf('Sending e-mails...\n');
% Send the email
for iContacts = 1:size(list,1)
    sendmail(list{iContacts,2},'Gift Exchange',...
        ['Hello ' list{iContacts,1} sprintf(',\n\n')...
        sprintf('This is  an e-mail autmoatically generated by MATLAB.\nYou will give a gift to: ')...
        list2{iContacts,1} sprintf('\nThe gift cost should be about $10')...
        sprintf('\n\n--\nThe organizing comitee\n')]);
end
fprintf('e-mails sent!\n');
% EOF


